# Generated by Django 5.1.2 on 2024-12-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_stockitem_count_stock_alter_dealerproductneed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalorder',
            name='note_amount',
            field=models.PositiveIntegerField(null=True, verbose_name='Add Note'),
        ),
    ]
