# Generated by Django 5.1.2 on 2024-12-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_finalorder_note_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalorder',
            name='note_write',
            field=models.CharField(max_length=200, null=True, verbose_name='Details for this amount'),
        ),
    ]
