# Generated by Django 5.1.2 on 2024-12-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_finalorder_note_write'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='note_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Product Factor'),
        ),
    ]
