# Generated by Django 5.1.2 on 2024-12-10 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_finalorder_note_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_address',
            field=models.TextField(null=True, verbose_name='Customer Address'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Customer Email'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(max_length=200, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_nid',
            field=models.CharField(max_length=20, null=True, verbose_name='Customer NID'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_owner',
            field=models.CharField(max_length=200, null=True, verbose_name='Customer Shop Owner'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_phone',
            field=models.CharField(max_length=15, null=True, verbose_name='Customer Phone'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.zone', verbose_name='Customer Zone'),
        ),
    ]
