# Generated by Django 5.1.2 on 2024-12-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_shop_shop_address_alter_shop_shop_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_owner',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Customer Shop Owner'),
        ),
    ]
