# Generated by Django 5.1.2 on 2024-12-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_shop_shop_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_address',
            field=models.TextField(blank=True, null=True, verbose_name='Customer Address'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Customer Email'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_nid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Customer NID'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Customer Phone'),
        ),
    ]
