# Generated by Django 5.1.2 on 2024-12-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_shop_shop_address_alter_shop_shop_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='note_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Received Amount'),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='note_write',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Take Note'),
        ),
    ]
