# Generated by Django 5.1.2 on 2024-12-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expenseAmount',
            field=models.PositiveIntegerField(null=True, verbose_name='Expense Amount'),
        ),
        migrations.AddField(
            model_name='order',
            name='expense_type',
            field=models.CharField(blank=True, choices=[('Transport', 'Transport'), ('Logistics', 'Logistics'), ('Miscellaneous', 'Miscellaneous')], default='Transport', max_length=20, null=True, verbose_name='EXPENSE TYPE CHOICES'),
        ),
    ]
