# Generated by Django 5.1.2 on 2024-12-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_order_expenseamount_order_expense_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expenseAmount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='expense_type',
        ),
    ]
