# Generated by Django 5.1.2 on 2024-12-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_remove_order_expenseamount_remove_order_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalorder',
            name='expense_Amount',
            field=models.PositiveIntegerField(null=True, verbose_name='Expense Amount'),
        ),
        migrations.AddField(
            model_name='finalorder',
            name='expense_type',
            field=models.CharField(blank=True, choices=[('Transport', 'Transport'), ('Logistics', 'Logistics'), ('Miscellaneous', 'Miscellaneous')], default='Transport', max_length=20, null=True, verbose_name='EXPENSE TYPE CHOICES'),
        ),
    ]
