# Generated by Django 5.1.2 on 2024-12-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_finalorder_expense_amount_finalorder_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerorder',
            name='expense_Amount',
            field=models.PositiveIntegerField(null=True, verbose_name='Expense Amount'),
        ),
        migrations.AddField(
            model_name='dealerorder',
            name='expense_type',
            field=models.CharField(blank=True, choices=[('Transport', 'Transport'), ('Logistics', 'Logistics'), ('Miscellaneous', 'Miscellaneous')], default='Transport', max_length=20, null=True, verbose_name='EXPENSE TYPE CHOICES'),
        ),
        migrations.AddField(
            model_name='dealerorder',
            name='note_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Received Amount'),
        ),
        migrations.AddField(
            model_name='dealerorder',
            name='note_write',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Take Note'),
        ),
    ]
