# Generated by Django 5.1.2 on 2024-12-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_dealerorder_expense_amount_dealerorder_expense_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_tp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Product TP'),
        ),
    ]
