# Generated by Django 5.1.2 on 2024-12-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_order_product_tp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_sku',
            field=models.CharField(max_length=100, verbose_name='Product SKU'),
        ),
    ]
